
name: 'airflow_dbt_warehouse'
version: '1.0.0'
config-version: 2

profile: 'airflow_dbt_warehouse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  airflow_dbt_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
